device: "cuda"
batch_size: 8
#batch_size: 100
test_batch_size: 10
epochs: 5
lr: 0.00004
momentum: 0.1
no_cuda: False
seed: 42
log_interval: 1

model_path: "../output/effb6-384-best-dropout_{}.bin"
model_backbone: "efficientnet"
model_name: "efficientnet-b6"

training_data_path: "../input/siic-isic-384x384-images/train/"
#training_data_path: "../input/siic-isic-768x768-images/train/"
#train_csv_fold: "../input/small_train_folds.csv"
train_csv_fold: "../input/train_folds_leak_free.csv"
#train_csv_fold: "../input/train_folds.csv"
test_data_path:  "../input/siic-isic-384x384-images/test/"
#test_data_path:  "../input/siic-isic-768x768-images/test/"
test_csv: "../input/siim-isic-melanoma-classification/test.csv"
#input_size: 768 
input_size: 384 
accumulation_steps: 4
supplement_data: False
swa:
  use_swa: False
  model_path: "../output/resnet18_test_swa_{}.bin"
fp16: True
num_classes: 1
use_metadata: False
tta: 10 
